# Generated by Django 5.2.1 on 2025-05-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_product_delete_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=2),
        ),
    ]
