# Generated by Django 5.2.1 on 2025-05-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='markets.size'),
        ),
    ]
