# Generated by Django 5.2.1 on 2025-05-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_size_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='markets.size'),
        ),
    ]
